Fix prefix param on rest methods
starkinfra/core-python pull request #23
Opened 2024-06-10 21:53 UTC by leoKagohara-Stark

2024-06-10 23:15 UTC, luistarkbank commented on tests/testRest.py
> +            prefix="Joker"
ue, não era pra estar importando ??

2024-06-10 23:20 UTC, luistarkbank commented on tests/testRest.py
> +            prefix="Joker"
recomendo colocar o joker no index

2024-06-11 13:42 UTC, leoKagohara-Stark commented on tests/testRest.py
> +            prefix="Joker"
é que tá no core coloquei o prefix ai pq é um parametro opcional, só para garantir que estamos passando no header e não está quebrando

2024-06-18 14:28 UTC, luistarkbank approved these changes

2024-06-18 14:59 UTC, luistarkbank requested changes

2024-06-18 14:59 UTC, luistarkbank commented on CHANGELOG.md
> +### Changed
eu esqueci de falar, mas precisa implementar o parse de de 500 pelo client, da uma olhada como eu fiz no de dotnet

2024-06-18 21:43 UTC, luistarkbank approved these changes

2024-06-19 15:57 UTC, merged